openapi: "3.0.3"
info:
  title: "Be_healthy API"
  description: "Be_healthy API"
  version: "1.0.0"
servers:
  - url: "https://be_healthy"
# - url: "https://localhost:8081"
paths:
  /api/users:
    get:
      summary: Метод получения списка пользователей
      operationId: "getAllUsers"
      responses:
        "200":
          description: Успешный ответ со списком пользователей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания пользователя
      operationId: "createUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Успешное добавление пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Пользователь с таким логином уже существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Метод обновления параметров пользователя
      operationId: "updateUser"
      responses:
        "200":
          description: Успешное обновление
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Метод обновления основной информации о пользователе
      operationId: "updateUserRole"
      responses:
        "200":
          description: Успешное обновление
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/users/{id}:
    get:
      summary: Метод получения пользователя
      operationId: "getUserById"
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
      responses:
        "200":
          description: Успешный ответ с информацией о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления пользователя
      operationId: "deleteUser"
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
      responses:
        "200":
          description: Успешное удаление
          content:
            application/json: { }
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Role:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: администратор
    kbju_norm:
      type: object
      properties:
        b:
          type: number
          example: 90.8
        u:
          type: number
          example: 250.1
        j:
          type: number
          example: 60.4
        k:
          type: number
          example: 2000.6
    User:
      type: object
      properties:
        id:
          type: number
          example: 2
        name:
          type: string
          example: Adam
        email:
          type: string
          example: adamsmith@gmail.com
        login:
          type: string
          example: adamsmith
        password:
          type: string
          example: $2a$12$YY2Egf4m6x5ET2l5.AnlAuQA1JkEZpMbCC/8DjbdHbDp4ZomqgU12
        avatar:
          type: string
          example: null
        base64image:
          type: string
          example: null
        weight:
          type: number
          example: 80.0
        height:
          type: number
          example: 180
        age:
          type: number
          example: 30
        activity:
          type: number
          example: 1.1
        sex:
          type: string
          enum:
            - женский
            - мужской
        goal:
          type: number
        role:
          $ref: "#/components/schemas/Role"
        calorieRec:
          type: number
          example: 1773
        carbRec:
          type: number
          example: 177
        kbju_norm:
          $ref: "#/components/schemas/kbju_norm"
        firstName:
          type: string
          example: Adam
        proteinRec:
          type: number
          example: 132
        fatRec:
          type: number
          example: 59
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"


